name: device_preview
version: 1.1.0
description: Approximate how your Flutter app looks and performs on another device.
homepage: https://github.com/aloisdeniel/flutter_device_preview

publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  device_frame:
    git:
      url: https://github.com/thanhle1547/flutter_device_preview
      path: device_frame
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
